// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace BlazorApp1.Model
{
    public partial class Product
    {
        public long ProductionId { get; set; }
        public int ProductQuantity { get; set; }
        public DateTime ProductDate { get; set; }
        public string ProductDescription { get; set; }
        public string ProductCode { get; set; }
    }
}