// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace BlazorApp1.Model
{
    public partial class Reject
    {
        public long RejectId { get; set; }
        public int RejectQuantity { get; set; }
        public DateTime RejectDate { get; set; }
        public string RejectDescription { get; set; }
        public string RejectCode { get; set; }
    }
}