// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace BlazorApp1.Model
{
    public partial class SqlDbContext : DbContext
    {
        public SqlDbContext()
        {
        }

        public SqlDbContext(DbContextOptions<SqlDbContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Product> TblProducts { get; set; }
        public virtual DbSet<Reject> TblRejects { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Product>(entity =>
            {
                entity.HasKey(e => e.ProductionId)
                    .HasName("PK_TBL_PRODUCTION");

                entity.ToTable("TBL_PRODUCTS");

                entity.Property(e => e.ProductionId).HasColumnName("production_id");

                entity.Property(e => e.ProductCode)
                    .IsRequired()
                    .HasColumnName("product_code")
                    .HasMaxLength(50);

                entity.Property(e => e.ProductDate)
                    .HasColumnName("product_date")
                    .HasColumnType("datetime");

                entity.Property(e => e.ProductDescription)
                    .IsRequired()
                    .HasColumnName("product_description")
                    .HasMaxLength(50);

                entity.Property(e => e.ProductQuantity).HasColumnName("product_quantity");
            });

            modelBuilder.Entity<Reject>(entity =>
            {
                entity.HasKey(e => e.RejectId);

                entity.ToTable("TBL_REJECTS");

                entity.Property(e => e.RejectId).HasColumnName("reject_id");

                entity.Property(e => e.RejectCode)
                    .IsRequired()
                    .HasColumnName("reject_code")
                    .HasMaxLength(50);

                entity.Property(e => e.RejectDate)
                    .HasColumnName("reject_date")
                    .HasColumnType("datetime");

                entity.Property(e => e.RejectDescription)
                    .IsRequired()
                    .HasColumnName("reject_description")
                    .HasMaxLength(50);

                entity.Property(e => e.RejectQuantity).HasColumnName("reject_quantity");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}